{% set name = "refurb" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/refurb-{{ version }}.tar.gz
  sha256: c1df310ad7f2627aed0a28e0821e3f693b7d93fa134c7d1484c81a81cb5413aa

build:
  entry_points:
    - refurb = refurb.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10
  run:
    - mypy >=0.981
    - python >=3.10
    - tomli >=2.0.1,<3.0.0

test:
  imports:
    - refurb
  commands:
    - pip check
    - refurb --help
  requires:
    - pip

about:
  home: https://github.com/dosisod/refurb
  summary: A tool for refurbish and modernize Python codebases
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - dosisod
