{% set name = "refurb" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/refurb-{{ version }}.tar.gz
  sha256: 1c97e3532159a131a4391b2d639c14e7be6fba28048f0ebdc57fb8552bd2aed0

build:
  entry_points:
    - refurb = refurb.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10,<4.0
  run:
    - mypy >=0.981,<0.982
    - python >=3.10,<4.0

test:
  imports:
    - refurb
  commands:
    - pip check
    - refurb --help
  requires:
    - pip

about:
  home: https://github.com/dosisod/refurb
  summary: A tool for refurbish and modernize Python codebases
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
