{% set name = "refurb" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/refurb-{{ version }}.tar.gz
  sha256: 9fb4dc340e475818a4d2a7f274c77b81861d2ed8115a3f4fabff53e0ee350aa1

build:
  entry_points:
    - refurb = refurb.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10
  run:
    - mypy >=0.981
    - python >=3.10
    - tomli >=2.0.1,<3.0.0

test:
  imports:
    - refurb
  commands:
    - pip check
    - refurb --help
  requires:
    - pip

about:
  home: https://github.com/dosisod/refurb
  summary: A tool for refurbishing and modernizing Python codebases
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - dosisod
