{% set name = "refurb" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/refurb-{{ version }}.tar.gz
  sha256: 1cd8d9aa69410d339cee02229aa02df14ecc2e13f0b8abfcdd4f69a7aa18ad2e

build:
  entry_points:
    - refurb = refurb.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10,<4.0
  run:
    - mypy >=0.981,<=0.991
    - python >=3.10,<4.0
    - tomli >=2.0.1,<3.0.0

test:
  imports:
    - refurb
  commands:
    - pip check
    - refurb --help
  requires:
    - pip

about:
  home: https://github.com/dosisod/refurb
  summary: A tool for refurbish and modernize Python codebases
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
